version: "3"

services:
  postgresdb:
    image: "postgres:12.0"
    container_name: data-postgresdb
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=data
    expose:
      - "5432"
    ports:
      - 5423:5432
#  autocoding-integration-test-db:
#    image: "postgres:12.0"
#    container_name: autocoding-it-db
#    environment:
#      - POSTGRES_USER=user
#      - POSTGRES_PASSWORD=password
#      - POSTGRES_DB=autocoding-it
#    expose:
#      - "5432"
#    ports:
#      - 5427:5432
#  rulesdb:
#    image: "postgres:12.0"
#    container_name: rules-postgresdb
#    environment:
#      - POSTGRES_USER=user
#      - POSTGRES_PASSWORD=password
#      - POSTGRES_DB=rules
#    expose:
#      - "5432"
#    ports:
#      - 5431:5432
#  rules-integration-test-db:
#    image: "postgres:12.0"
#    container_name: rules-it-db
#    environment:
#      - POSTGRES_USER=user
#      - POSTGRES_PASSWORD=password
#      - POSTGRES_DB=rules-it
#    expose:
#      - "5432"
#    ports:
#      - 5425:5432
#  audit-logsdb:
#    image: "postgres:12.0"
#    container_name: auditlogs-db
#    environment:
#      - POSTGRES_USER=user
#      - POSTGRES_PASSWORD=password
#      - POSTGRES_DB=audit-logs
#    expose:
#      - "5432"
#    ports:
#      - 5430:5432
#  audit-logs-integration-test-db:
#    image: "postgres:12.0"
#    container_name: audit-logs-integration-test-db
#    environment:
#      - POSTGRES_USER=user
#      - POSTGRES_PASSWORD=password
#      - POSTGRES_DB=audit-logs-it
#    expose:
#      - "5432"
#    ports:
#      - 5424:5432
#  #  sqs:
#  #    image: roribio16/alpine-sqs
#  #    ports:
#  #      - "9324:9324"
#  #      - "9325:9325"
#  #    volumes:
#  #      - ./elasticmq.conf:/opt/config/elasticmq.conf
#  autoingest:
#    image: "postgres:12.0"
#    container_name: autoingest-db
#    environment:
#      - POSTGRES_USER=user
#      - POSTGRES_PASSWORD=password
#      - POSTGRES_DB=autoingest
#    expose:
#      - "5432"
#    ports:
#      - 5429:5432
#  autoingest-integration-test-db:
#    image: "postgres:12.0"
#    container_name: autoingest-it-db
#    environment:
#      - POSTGRES_USER=user
#      - POSTGRES_PASSWORD=password
#      - POSTGRES_DB=autoingest-it
#    expose:
#      - "5432"
#    ports:
#      - 5426:5432
#  reporting:
#    image: "postgres:12.0"
#    container_name: reporting-db
#    environment:
#      - POSTGRES_USER=user
#      - POSTGRES_PASSWORD=password
#      - POSTGRES_DB=reporting
#    expose:
#      - "5432"
#    ports:
#      - 5428:5432
#  postgres:
#    image: "postgres:12.0"
#    container_name: airflow-db
#    environment:
#      - POSTGRES_USER=airflow
#      - POSTGRES_PASSWORD=airflow
#      - POSTGRES_DB=airflow
#    expose:
#      - "5432"
#    ports:
#      - 5421:5432
#  webserver:
#    container_name: airflow-webserver
#    image: puckel/docker-airflow
#    build:
#      context: https://github.com/puckel/docker-airflow.git
#      dockerfile: Dockerfile
#      args:
#        AIRFLOW_DEPS: gcp_api,s3
#        PYTHON_DEPS: sqlalchemy==1.3.2
#    restart: always
#    depends_on:
#      - postgres
#    environment:
#      - LOAD_EX=n
#      - EXECUTOR=Local
#      - FERNET_KEY=jsDPRErfv8Z_eVTnGfF8ywd19j4pyqE3NpdUBA_oRTo=
#      - AIRFLOW__CORE__LOGGING_LEVEL=INFO
#    volumes:
#      - ./data_integration/dag_scripts:/usr/local/airflow/dags
#      - ./clinical-notes/:/clinical-notes-local
#      # Uncomment to include custom plugins
#      # - ./plugins:/usr/local/airflow/plugins
#    ports:
#      - "8065:8080"
#    command: webserver
#    healthcheck:
#      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
#      interval: 30s
#      timeout: 30s
#      retries: 3
#  redis:
#    container_name: redis
#    image: redis:7.0.2
#    ports:
#      - "6379:6379"
#    command: redis-server --requirepass password --save 20 1 --loglevel warning

volumes:
  db:
    driver: local
