spring:
  main:
    banner-mode: off
  datasource:
    ## PostgreSQL
    url: jdbc:postgresql://localhost:5423/data
    username: user
    password: password
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      #option create will drop n create table again, good for testing, comment this in production
      #update
      ddl-auto: create
    properties:
      hibernate:
        # The SQL dialect makes Hibernate generate better SQL for the chosen database
        dialect: org.hibernate.dialect.PostgreSQLDialect
        order_inserts: true
        jdbc:
          batch_size: 30